spring.application.name=accounting-service
server.port=${SERVER_PORT:8082}

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=${DDL_AUTO:update}
spring.jpa.open-in-view=false
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.default_schema=${DB_SCHEMA:accounting}

accounting.grpc.port=${ACCOUNTING_GRPC_PORT:9092}

accounting.reports.dir=${ACCOUNTING_REPORTS_DIR:./reports}

management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always
